# Generated by Django 6.1.1 on 2026-10-01 16:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(max_length=16, unique=True, verbose_name='OPIS Truckstop ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada')], default='US', max_length=2)),
                ('rack_id', models.CharField(blank=True, max_length=16)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('geocode_source', models.CharField(choices=[('census_gazetteer', 'US Census Gazetteer'), ('geonames', 'GeoNames populated place'), ('geonames_landmark', 'GeoNames landmark proxy'), ('nominatim', 'Nominatim')], max_length=32)),
                ('geocode_ambiguity_miles', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'truck stop',
                'ordering': ['opis_id'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='truckstop_lat_lon_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__gte', -90.0), ('latitude__lte', 90.0)), name='truckstop_latitude_in_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180.0), ('longitude__lte', 180.0)), name='truckstop_longitude_in_range')],
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd_per_gallon', models.DecimalField(decimal_places=8, max_digits=12)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='fuelroute.truckstop')),
            ],
            options={
                'verbose_name': 'price observation',
                'constraints': [models.CheckConstraint(condition=models.Q(('price_usd_per_gallon__gt', Decimal('0'))), name='priceobservation_price_positive')],
            },
        ),
    ]
